package app

import (
	"encoding/json"
	"fmt"
	"net/url"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

type flutterPluginDependencies struct {
	Plugins struct {
		IOS []flutterPluginDependency `json:"ios"`
	} `json:"plugins"`
}

type flutterPluginDependency struct {
	Name string `json:"name"`
	Path string `json:"path"`
}

type flutterPluginPubspec struct {
	Flutter struct {
		Plugin struct {
			Platforms map[string]flutterPluginPlatform `yaml:"platforms"`
		} `yaml:"plugin"`
	} `yaml:"flutter"`
}

type flutterPluginPlatform struct {
	DartPluginClass string `yaml:"dartPluginClass"`
	DartFileName    string `yaml:"dartFileName"`
}

type dartPluginRegistration struct {
	Name     string
	Class    string
	FileName string
}

func generateDartPluginRegistrant(project project) (string, error) {
	dependenciesPath := filepath.Join(project.Root, ".flutter-plugins-dependencies")
	data, err := os.ReadFile(dependenciesPath)
	if os.IsNotExist(err) {
		return "", nil
	}
	if err != nil {
		return "", fmt.Errorf("read %s: %w", dependenciesPath, err)
	}

	var dependencies flutterPluginDependencies
	if err := json.Unmarshal(data, &dependencies); err != nil {
		return "", fmt.Errorf("parse %s: %w", dependenciesPath, err)
	}

	registrations := make([]dartPluginRegistration, 0, len(dependencies.Plugins.IOS))
	seen := make(map[string]bool)
	for _, plugin := range dependencies.Plugins.IOS {
		if plugin.Name == "" || plugin.Path == "" || seen[plugin.Name] {
			continue
		}
		pubspecPath := filepath.Join(plugin.Path, "pubspec.yaml")
		pubspecData, err := os.ReadFile(pubspecPath)
		if err != nil {
			return "", fmt.Errorf("read Dart plugin metadata %s: %w", pubspecPath, err)
		}
		var pubspec flutterPluginPubspec
		if err := yaml.Unmarshal(pubspecData, &pubspec); err != nil {
			return "", fmt.Errorf("parse Dart plugin metadata %s: %w", pubspecPath, err)
		}
		platform, ok := pubspec.Flutter.Plugin.Platforms["ios"]
		if !ok || strings.TrimSpace(platform.DartPluginClass) == "" {
			continue
		}
		fileName := strings.TrimSpace(platform.DartFileName)
		if fileName == "" {
			fileName = plugin.Name + ".dart"
		}
		registrations = append(registrations, dartPluginRegistration{
			Name:     plugin.Name,
			Class:    strings.TrimSpace(platform.DartPluginClass),
			FileName: fileName,
		})
		seen[plugin.Name] = true
	}

	if len(registrations) == 0 {
		return "", nil
	}
	sort.Slice(registrations, func(i, j int) bool { return registrations[i].Name < registrations[j].Name })

	var out strings.Builder
	out.WriteString("//\n// Generated file. Do not edit.\n// Generated by ripley for Dart-side iOS plugin registration.\n//\n\n")
	out.WriteString("import 'dart:io'; // flutter_ignore: dart_io_import.\n")
	for _, plugin := range registrations {
		fmt.Fprintf(&out, "import 'package:%s/%s' as %s;\n", plugin.Name, plugin.FileName, plugin.Name)
	}
	out.WriteString("\n@pragma('vm:entry-point')\nclass _PluginRegistrant {\n")
	out.WriteString("  @pragma('vm:entry-point')\n  static void register() {\n")
	out.WriteString("    if (Platform.isIOS) {\n")
	for _, plugin := range registrations {
		out.WriteString("      try {\n")
		fmt.Fprintf(&out, "        %s.%s.registerWith();\n", plugin.Name, plugin.Class)
		out.WriteString("      } catch (err) {\n")
		fmt.Fprintf(&out, "        print('`%s` threw an error: $err. The app may not function as expected until you remove this plugin from pubspec.yaml');\n", plugin.Name)
		out.WriteString("      }\n\n")
	}
	out.WriteString("    }\n  }\n}\n")

	path := filepath.Join(project.DartTool, "flutter_build", "dart_plugin_registrant.dart")
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return "", err
	}
	if err := os.WriteFile(path, []byte(out.String()), 0o644); err != nil {
		return "", err
	}
	return path, nil
}

func dartPluginRegistrantFrontendArgs(path string) []string {
	if path == "" {
		return nil
	}
	uri := (&url.URL{Scheme: "file", Path: filepath.ToSlash(path)}).String()
	return []string{
		"--source", uri,
		"--source", "package:flutter/src/dart_plugin_registrant.dart",
		"-Dflutter.dart_plugin_registrant=" + uri,
	}
}
